### PR TITLE
Update shared-promise-scopes.ts

### PR DESCRIPTION
**Pull request by lorensr**
Is my change equivalent? If so, it's more familiar, and I imagine more common.

### CODE REVIEW

**Comment by bergundy** [comment]
@lorensr I'd rather keep the `await`s because it includes `main` in the stack trace in case of an error:
https://github.com/temporalio/sdk-node/pull/158#discussion_r669769124

**Comment by lorensr** [comment]
Ah, I see, thanks. What about `await scopePromise` instead of `return await scopePromise`?

**Comment by bergundy** [comment]
I'd just leave as is TBH

**Comment by bergundy** [comment]
Maybe change to just "unless awaited"?
I guess you could say returned but then it is still awaited by the workflow runtime

**Comment by lorensr** [comment]
Got it, updated

**Review by sw-yx — APPROVED** [review]

**Review by bergundy — APPROVED** [review]
Thanks @lorensr, please make sure you fix the commit message to use conventional commits: https://github.com/temporalio/sdk-node/blob/main/CONTRIBUTING.md#style-guide
Note that we require sentence case for the message (not mentioned in CONTRIBUTING.md) so the commit message should be: `chore(samples): Update comment in shared-promise-scopes.ts`

**Comment by lorensr** [comment]
> Thanks @lorensr, please make sure you fix the commit message to use conventional commits: https://github.com/temporalio/sdk-node/blob/main/CONTRIBUTING.md#style-guide
> Note that we require sentence case for the message (not mentioned in CONTRIBUTING.md) so the commit message should be: `chore(samples): Update comment in shared-promise-scopes.ts`

Gotcha, thanks. Sorry—when I got stuck on the `npm run build` step, I didn't finish reading it! Updated commit message & CONTRIBUTING

**Comment by bergundy** [comment]
This is approved, you can merge once you rebase and ci passes

**Comment by lorensr** [comment]
I can't run workflows yet or merge, but I rebased

image

**Comment by sw-yx** [comment]
i clicked the run thingy

**Comment by lorensr** [comment]
`npm test` failed on the below, which seems unrelated and passes locally, so maybe a flaky test—I'm guessing it will pass when rerun.

```
@temporalio/test:   integration › WorkflowOptions are passed correctly
@temporalio/test:   Returned promise rejected with unexpected exception:
@temporalio/test:   Error {
@temporalio/test:     code: 3,
@temporalio/test:     details: 'CustomIntField is not a valid search attribute name',
@temporalio/test:     metadata: Metadata {
@temporalio/test:       internalRepr: Map {
@temporalio/test:         'content-type' => Array [ … ],
@temporalio/test:       },
@temporalio/test:       options: {},
@temporalio/test:     },
@temporalio/test:     message: '3 INVALID_ARGUMENT: CustomIntField is not a valid search attribute name',
@temporalio/test:   }
@temporalio/test:   Expected instance of:
@temporalio/test:   Function WorkflowExecutionTimedOutError {}
@temporalio/test:   › Object.callErrorFromStatus (/home/runner/work/sdk-node/sdk-node/node_modules/@grpc/grpc-js/src/call.ts:81:24)
@temporalio/test:   › Object.onReceiveStatus (/home/runner/work/sdk-node/sdk-node/node_modules/@grpc/grpc-js/src/client.ts:338:36)
@temporalio/test:   › Object.onReceiveStatus (/home/runner/work/sdk-node/sdk-node/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
@temporalio/test:   › Object.onReceiveStatus (/home/runner/work/sdk-node/sdk-node/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
@temporalio/test:   › /home/runner/work/sdk-node/sdk-node/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
@temporalio/test:   ─
@temporalio/test:   1 test failed
@temporalio/test:   3 tests todo
lerna ERR! npm run test exited 1 in '@temporalio/test'
Error: Process completed with exit code 1.
```

**Comment by bergundy** [comment]
@lorensr I see this branch has gone out-of-date, the PR is approved, merge at will.

**Comment by lorensr** [comment]
Updated

@bergundy I don't have write access to any repos

image

**Comment by bergundy** [comment]
Rebased this and merged without a PR

**Pull request closed without merging**
